version: '3'

services:
  api:
    container_name: devlied_api
    image: registry.gitlab.com/jesusandres31/devlied/backend:latest
    restart: always
    depends_on:
      - db
  app:
    container_name: devlied_app
    image: registry.gitlab.com/jesusandres31/devlied/frontend:latest
    restart: always
    depends_on:
      - api
  nginx:
    container_name: devlied_nginx
    image: registry.gitlab.com/jesusandres31/devlied/nginx:latest
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - api
      - app
